/* Default CSS */
/* Generated by the CoffeeCup HTML Editor - www.coffeecup.com */

body { margin:0; }
header{background:#004080; float:left;width:100%;}
.cartsummary{float:right;color:white; }

list{float:left;width:60%;min-height:700px; }
cart{float:right;width:38%;border-left:1px solid gray; min-height:200px; margin-bottom:20px;}

purchased{float:right;width:38%;border-left:1px solid gray; min-height:200px;}

cart{float:right;width:38%;border-left:1px solid gray; }

itemname,price,remitem,buy{float:left;width:25%; }

.dialog{display:none;position:absolute;top:20%;width:60%;margin-left:20%;background:white;border:5px solid gray;padding:20px; }
closedialog{float:right;background:red;color:white;padding:10px; }
.selected_item{ float:left;width:100%;background:#FFFF80;border-bottom:1px solid lightgray;}
.selected_item_total{background:#C0FFC0;font-weight:bold;}
.item_name,.item_price,.item_quantity,.item_total,.item_cancel,.item_buy_from_cart{float:left;width:16%; }
.item_total{text-align:right;}
.remove{margin-left:50%;}
.search{float:left;width:50%;margin-left:20%;}
.items_datalist{float:left;width:100%;border:1px solid gray;height:30px; margin-top:5px;}
